### ISSUE TITLE
Add more example features to card or card modal?

### ISSUE THREAD

**Issue by cmilkaitis** [starboardcoop/things-app#13]
What else could a user expect to see on card?
- Item availability
- Calendar for reservations on specific date
- Original Price of Item
- Links to DIY projects that require the item
- Links to how to use items

**Comment by dillonfagan** [comment]
The big we're running into (where a fixed-position div isn't taking up the whole screen) seems to be caused by the styles `transform-scale-x` and `transform-scale-y`, which are being inherited from div.

**Comment by dillonfagan** [comment]
**Update:** the cause is a weird CSS conflict, either a fault of the spec or the browser. **If a fixed element is within an element that does a scale animation, then it ignores the fixed style.**

A workaround for us would be to add a wrapping div around the existing Card layout and the Modal, so that what scales is the Card and not the Modal.
